baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'raml.online'

[permalinks]
    journal = "/:filename/"


# See https://feathericons.com/
# The value of pre is the icon name
[menu]
  [[menu.main]]
    name = "Home"
    pre = "home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "About"
    pre = "compass"
    url = "/about/"
    weight = 2
  [[menu.main]]
    name = "Journal"
    pre = "edit"
    url = "/journal/"
    weight = 3
  [[menu.main]]
    name = "Showcase"
    pre = "code"
    url = "/showcase/"
    weight = 4
  [[menu.main]]
    name = "Tags"
    pre = "tag"
    url = "/tags/"
    weight = 5

[taxonomies]
  tag = "tags"

[params]
  dateFormat = "Jan 2, 2006"
  homeText = "My Online Journal and Portfolio"
